### ISSUE TITLE
layerData tile (x,y) seem off

### ISSUE THREAD

**Issue by schell** [chrra/htiled#10]
First off - thanks for writing this sweet tool!

Now, I'm not sure if this is a bug or a misunderstanding of the tmx format on my part. It seems that the `layerData`'s `Map (Int,Int) Tile` has its indices slightly off. I'm looking at my 'floor' layer's top left tile, which has an (x,y) of (1,2) and an index of 21 (gid of 22), which you can see in the Tiled screenshot below:

<img width="1495" alt="screenshot 2016-07-08 12 15 59" src="https://cloud.githubusercontent.com/assets/24942/16698998/267231ee-4506-11e6-82cd-7ba1d8456f86.png">
(it's the top left tile in the set as well as the bluish tile near the top left of the map)

but when I print the 'floor's layerData the top left tile seems to have an (x,y) of (9, 6):
```haskell
fromList
  [ ( ( 9 , 6 )
    , Tile
        { tileGid = 22
        , tileIsVFlipped = False
        , tileIsHFlipped = False
        , tileIsDiagFlipped = False
        }
    )
  , ( ( 9 , 7 )
    , Tile
        { tileGid = 142
        , tileIsVFlipped = False
        , tileIsHFlipped = False
        , tileIsDiagFlipped = False
        }
    )
-- ...
```
Any thoughts?

**Comment by schell** [comment]
You can see my *.tmx file here https://github.com/schell/odin/blob/master/assets/oryx_ultimate_fantasy/uf_examples/uf_example_1.tmx

**Comment by schell** [comment]
Pull request https://github.com/chrra/htiled/pull/11 fixes this issue, and now everything seems to work fine :)

<img width="912" alt="screenshot 2016-07-08 14 41 56" src="https://cloud.githubusercontent.com/assets/24942/16702370/5b7167f2-451a-11e6-974e-f44f287e9cd5.png">

**Comment by m09** [comment]
Thanks for the issue and the PR!

If you're interested in getting access, please let us know :) as I said in your previous issue @chrra and I don't use tiled anymore for quite some time now so it might make your life easier.

**Comment by schell** [comment]
Thanks @m09. What do you guys use now? Or did you just stop making tile-based games?

I would definitely like access, it looks like I'll be using htiled for my next project.

**Comment by m09** [comment]
I personally stopped making tile-based games and can't speak for @chrra!

As for the access, I'll be able to give you maintainer rights on hackage (if you give me a username) but can't do anything for this repo. If @chrra doesn't drop by to add you maybe we can just change the head of the repo on hackage and work from a fork :)

**Comment by schell** [comment]
Okay, cool. My hackage username is SchellScivally.

**Comment by m09** [comment]
Hackage side should be handled. Let me know if you want me to push your PR as a new version btw.

**Comment by schell** [comment]
Yes please, thanks!

**Comment by m09** [comment]
Should be good.

**Comment by chrra** [comment]
Collaborator invite sent. Welcome aboard.
