### ISSUE TITLE
Change Layer representation to Vector

### ISSUE THREAD

**Issue by scan** [chrra/htiled#4]
Currently, we're using [`Data.Map`](https://github.com/chrra/htiled/blob/master/src/Data/Tiled/Types.hs#L66) for the representation of the tiles. `Map` is only efficient with sparse data and random lookups on a single tile, but usually, when using tile maps, it is more important to have a fast way to slice and traverse data.

Perhaps it'd be a better idea to switch to [`Data.Vector`](http://hackage.haskell.org/packages/archive/vector/latest/doc/html/Data-Vector.html) or to an `Array`. The `Array` would allow for a more dense representation and still keep the 2D-Index. `Vector` would require some more complex calculations on slicing, since it only supports a scalar index.

What do you think?

**Comment by schell** [comment]
I know this is probably long gone but it seems to me like this would be the job of the renderer, and not `htiled`, am I right? You can always extract the layer data and build a vector. That said I'm not against using vectors (especially if there is an implementation waiting).

**Comment by schell** [comment]
I just went ahead and did this.
